# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
      
version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout # check out the code in the project directory
      - run: echo "ci finished" # run the `echo` command